/* --- Anime-Themed CSS with Gradient Background --- */

/* Body Styling */
body {
    font-family: 'Roboto Mono', monospace; /* Install via Google Fonts */
    background: linear-gradient(135deg, #6a11cb, #2575fc, #ff6ec4);
    background-size: 300% 300%; /* Create a smooth gradient animation */
    animation: gradientAnimation 10s ease infinite; /* Infinite loop */
    color: #f4f4f4;
    margin: 0;
    padding: 0;
    line-height: 1.6;
}

/* Header Styling */
header {
    background: rgba(0, 0, 0, 0.6); /* Transparent black overlay */
    padding: 20px 0;
    text-align: center;
    color: #fff;
    font-size: 2.5em;
    letter-spacing: 2px;
    text-shadow: 2px 2px 8px #000;
    border-bottom: 3px solid #ff69b4; /* Anime pink highlight */
}

/* Navigation Bar */
nav {
    display: flex;
    justify-content: center;
    background: rgba(0, 0, 0, 0.8);
    padding: 10px 0;
}

nav a {
    color: #ff69b4; /* Anime pink */
    text-decoration: none;
    margin: 0 15px;
    font-weight: bold;
    font-size: 1.2em;
    transition: color 0.3s ease;
}

nav a:hover {
    color: #ffd700; /* Golden highlight */
}

/* Main Content */
main {
    padding: 30px;
    background: rgba(255, 255, 255, 0.9);
    border-radius: 10px;
    max-width: 800px;
    margin: 30px auto;
    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
}

h1, h2, h3 {
    color: #ff69b4;
    text-align: center;
    text-shadow: 1px 1px 5px rgba(0, 0, 0, 0.6);
}

/* Anime Card Section */
.card {
    background: rgba(0, 0, 0, 0.7);
    color: #fff;
    padding: 20px;
    border-radius: 15px;
    text-align: center;
    margin: 20px 0;
    box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.5);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: scale(1.05);
    box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.7);
}

/* Buttons */
.button {
    display: inline-block;
    background: #ff69b4;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    text-transform: uppercase;
    font-weight: bold;
    cursor: pointer;
    transition: background 0.3s ease;
}

.button:hover {
    background: #ffd700;
}

/* Footer */
footer {
    text-align: center;
    padding: 10px 0;
    background: rgba(0, 0, 0, 0.9);
    color: #fff;
    font-size: 0.9em;
    position: fixed;
    bottom: 0;
    width: 100%;
    border-top: 2px solid #ff69b4;
}

/* Anime Glow Animation */
.glow {
    text-shadow: 0 0 10px #ff69b4, 0 0 20px #ff69b4, 0 0 30px #ff69b4, 0 0 40px #ff69b4;
    animation: glow-animation 1.5s infinite alternate;
}

@keyframes glow-animation {
    0% {
        text-shadow: 0 0 5px #ff69b4, 0 0 10px #ff69b4, 0 0 20px #ff69b4;
    }
    100% {
        text-shadow: 0 0 15px #ff69b4, 0 0 25px #ff69b4, 0 0 35px #ff69b4;
    }
}

/* Gradient Animation */
@keyframes gradientAnimation {
    0% {
        background-position: 0% 50%;
    }
    50% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
}
